[package]
name = "streamfusion-kafka"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
streamfusion-bridge = { path = "../bridge" }
arrow = { workspace = true, features = ["json"] }
jni.workspace = true
arrow-avro.workspace = true
prost-reflect.workspace = true
prost.workspace = true
prost-types.workspace = true
chrono.workspace = true
base64.workspace = true
serde_json.workspace = true
memchr.workspace = true

[dependencies.libmimalloc-sys]
workspace = true
optional = true

[build-dependencies]
streamfusion-native-build = { path = "../native-build" }

[features]
default = []
mimalloc = ["dep:libmimalloc-sys", "libmimalloc-sys/v2"]

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "kafka_sink"
harness = false
