[package]
name = "streamfusion-format-support"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
streamfusion-bridge = { path = "../bridge" }
arrow.workspace = true
jni.workspace = true

[dev-dependencies]
criterion.workspace = true
streamfusion-benchmark-support.workspace = true

[[bench]]
name = "raw_decode"
harness = false
