<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>tech.streamfusion</groupId><artifactId>StreamFusion</artifactId><version>${revision}</version></parent>
    <artifactId>streamfusion-json</artifactId>
    <name>StreamFusion JSON</name>
    <properties><native.test.resource.skip>true</native.test.resource.skip></properties>
    <dependencies><dependency><groupId>tech.streamfusion</groupId><artifactId>streamfusion-core</artifactId><version>${project.version}</version><scope>provided</scope></dependency></dependencies>
    <build>
        <sourceDirectory>${project.basedir}/../src/main/java</sourceDirectory>
        <resources combine.self="override">
            <resource><directory>${project.basedir}/src/main/resources</directory></resource>
            <resource><directory>${project.basedir}/../native/target/universal/json</directory><targetPath>tech/streamfusion/native/json</targetPath><includes><include>**/libstreamfusion_json.so</include><include>**/libstreamfusion_json.dylib</include></includes></resource>
        </resources>
        <plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><version>3.13.0</version><configuration><includes><include>tech/streamfusion/format/json/**/*.java</include></includes></configuration></plugin></plugins>
    </build>
</project>
