[package]
name = "streamfusion-orc"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
streamfusion-bridge = { path = "../bridge" }
arrow.workspace = true
jni.workspace = true
orc-rust = { version = "=0.9.0", default-features = false }
arrow59 = { package = "arrow", version = "59", default-features = false, features = ["ffi"] }
bytes.workspace = true
prost13 = { package = "prost", version = "0.13" }

[dependencies.libmimalloc-sys]
workspace = true
optional = true

[build-dependencies]
streamfusion-native-build = { path = "../native-build" }

[features]
default = []
mimalloc = ["dep:libmimalloc-sys", "libmimalloc-sys/v2"]
reader-comparison = []
writer-comparison = []

[dev-dependencies]
criterion.workspace = true
streamfusion-benchmark-support.workspace = true

[[bench]]
name = "normalization"
harness = false
